<!-- Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 ./laptop_materia.glb
Author: DimenVision (https://sketchfab.com/DimenVision)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/laptop-05ad6b27aff646deaea29cc8c6bfa6fa
Title: Laptop -->

<script>
    import { T } from '@threlte/core';
    import { useGltf } from '@threlte/extras';
    import * as THREE from 'three';
  
    let {
        icons,
        fallback,
        error,
        children,
        ref = $bindable(),
        ...props
    } = $props();
  
    const gltf = useGltf('assets/laptop_materia.glb');
  
    // Flag to toggle all Black_Dark materials
    let showBlackDark = true;
  
    // Constants for canvas size
    const CANVAS_WIDTH = 1920;
    const CANVAS_HEIGHT = 1080;
  
    // Function to create a black square texture with all icons
    const createBlackSquareMaterial = () => {
        const canvas = document.createElement('canvas');
        const context = canvas.getContext('2d');
  
        // Set canvas size
        canvas.width = CANVAS_WIDTH;
        canvas.height = CANVAS_HEIGHT;
  
        // Fill the calibrated rectangle (representing the screen)
        context.fillStyle = 'blue';
        const rectX = (canvas.width / CANVAS_WIDTH) * 270; // Adjusted X position
    const rectY = (canvas.height / CANVAS_HEIGHT) * 290; // Adjusted Y position
    const rectWidth = (canvas.width / CANVAS_WIDTH) * 425;
    const rectHeight = (canvas.height / CANVAS_HEIGHT) * 225;

        context.fillRect(rectX, rectY, rectWidth, rectHeight);
  
        // Enhance contrast by applying a shadow effect for icons
        context.shadowColor = 'rgba(0, 0, 0, 1)';
        context.shadowBlur = 10;
        context.shadowOffsetX = 2;
        context.shadowOffsetY = 2;
  
        // Apply filters for color enhancement
        context.filter = 'brightness(1) saturate(4)';
  
        // Calculate icon size and positioning
        const iconSize = rectHeight / 4; // Fit icons within rectangle height
        const totalWidth = iconSize * icons.length + (icons.length - 1) * 20;
        const startX = rectX + rectWidth / 2 - totalWidth / 2; // Center icons in the rectangle
        const centerY = rectY + rectHeight / 2 - iconSize / 2;
  
        // Draw icons dynamically on the canvas
        icons.forEach((iconName, index) => {
            const iconUrl = `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${iconName.split('-')[1]}/${iconName.split('-')[1]}-original.svg`;
            const icon = new Image();
            icon.crossOrigin = 'anonymous'; // Prevent CORS issues
            icon.src = iconUrl;
            icon.onload = () => {
                const x = startX + index * (iconSize + 20); // Arrange icons in a row
                context.drawImage(icon, x, centerY, iconSize, iconSize);
                texture.needsUpdate = true;
            };
        });
  
        const texture = new THREE.CanvasTexture(canvas);
        texture.needsUpdate = true;
  
        return new THREE.MeshBasicMaterial({ map: texture });
    };
  
    const blackDarkMaterial = createBlackSquareMaterial();
  </script>
  
  <T.Group bind:ref dispose={false} {...props}>
    {#await gltf}
        {@render fallback?.()}
    {:then gltf}
        <T.Group position={[-0.19, 1.1, -0.19]} rotation={[0.84, -0.44, 0.15]}>
            <T.Group position={[0, 0.5, -1.02]} rotation={[-2.17, 0, 0]}>
                <T.Mesh geometry={gltf.nodes.Object_33.geometry} material={gltf.materials.Blue} />
                {#if showBlackDark}
                    <!-- Apply the black square material with icons to Object_34 -->
                    <T.Mesh geometry={gltf.nodes.Object_34.geometry} material={blackDarkMaterial} />
                {/if}
            </T.Group>
            <T.Mesh geometry={gltf.nodes.Object_23.geometry} material={gltf.materials.Blue} />
            <T.Mesh geometry={gltf.nodes.Object_24.geometry} material={gltf.materials.Orange} />
            <T.Mesh geometry={gltf.nodes.Object_25.geometry} material={gltf.materials.White} />
            <T.Mesh geometry={gltf.nodes.Object_26.geometry} material={gltf.materials.Yellow} />
            <T.Mesh geometry={gltf.nodes.Object_27.geometry} material={gltf.materials.Blue_Dark} />
            <T.Mesh geometry={gltf.nodes.Object_29.geometry} material={gltf.materials['.Example_Sheet_033.001']} />
            <T.Mesh geometry={gltf.nodes.Object_31.geometry} material={gltf.materials['.Example_Sheet_033.001']} />
            {#if showBlackDark}
                <T.Mesh geometry={gltf.nodes.Object_36.geometry} material={material} position={[0.96, 0.06, -0.68]} rotation={[-2.17, 0, 0]} />
                <T.Mesh geometry={gltf.nodes.Object_38.geometry} material={material} position={[0.96, 0.98, -1.31]} rotation={[-2.17, 0, 0]} />
                <T.Mesh geometry={gltf.nodes.Object_40.geometry} material={material} position={[-0.95, 0.98, -1.31]} rotation={[-2.17, 0, 0]} />
                <T.Mesh geometry={gltf.nodes.Object_42.geometry} material={material} position={[-0.95, 0.06, -0.68]} rotation={[-2.17, 0, 0]} />
            {/if}
        </T.Group>
        <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Yellow} position={[-0.48, 0.2, 0.02]} />
        <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.Orange} position={[0.95, 0.36, 0.12]} />
        <T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.Yellow} position={[-1.42, 1.82, -0.04]} />
        <T.Mesh geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.Yellow} position={[1.56, 1.66, 0.26]} />
        <T.Mesh geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.Orange} position={[-0.82, 3.27, -0.18]} />
        <T.Mesh geometry={gltf.nodes.Object_14.geometry} material={gltf.materials.Yellow} position={[1.13, 0.86, -0.03]} rotation={[1.86, 0.66, 2.68]} />
        <T.Mesh geometry={gltf.nodes.Object_16.geometry} material={gltf.materials.Orange} position={[0.74, 3.1, -0.01]} rotation={[1.11, -1.11, 2.87]} />
        <T.Mesh geometry={gltf.nodes.Object_18.geometry} material={gltf.materials.Orange} position={[-1.38, 0.23, 0.06]} rotation={[-0.16, 1.19, 1.79]} />
        <T.Mesh geometry={gltf.nodes.Object_20.geometry} material={gltf.materials.Yellow} position={[-1.36, 2.73, 0.08]} rotation={[-3, 0.81, -0.47]} />
    {:catch err}
        {@render error?.({ error: err })}
    {/await}
  
    {@render children?.({ ref })}
  </T.Group>
  