
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 ./old_laptop.glb
Author: Anom Purple Modelling (https://sketchfab.com/Anom404)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/old-laptop-efc28e11db56473399fd70545ee10f16
Title: Old Laptop
-->




    <script>
				
	
	
  
        import { T } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        } = $props()

				

				

        

        const gltf = useGltf('/old_laptop.glb')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Group rotation={[-Math.PI / 2, 0, Math.PI / 2,]} scale={15.62} >
<T.Group rotation={[Math.PI / 2, 0, 0,]} scale={0.01} >
<T.Mesh geometry={gltf.nodes.Cubo001_Materiais_0.geometry} material={gltf.materials.Materiais} rotation={[Math.PI / 2, 0.99, -Math.PI,]} scale={100} />

</T.Group>

</T.Group>

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	